<?php


namespace Kosherdev\Calendar\Constants;


class TorahParshioys
{

    const transliteratedParshios = [
        "Bereshis",
        "Noach",
        "Lech Lecha",
        "Vayera",
        "Chayei Sara",
        "Toldos",
        "Vayetzei",
        "Vayishlach",
        "Vayeshev",
        "Miketz",
        "Vayigash",
        "Vayechi",
        "Shemos",
        "Vaera",
        "Bo",
        "Beshalach",
        "Yisro",
        "Mishpatim",
        "Terumah",
        "Tetzaveh",
        "Ki Sisa",
        "Vayakhel",
        "Pekudei",
        "Vayikra",
        "Tzav",
        "Shmini",
        "Tazria",
        "Metzora",
        "Achrei Mos",
        "Kedoshim",
        "Emor",
        "Behar",
        "Bechukosai",
        "Bamidbar",
        "Nasso",
        "Beha'aloscha",
        "Sh'lach",
        "Korach",
        "Chukas",
        "Balak",
        "Pinchas",
        "Matos",
        "Masei",
        "Devarim",
        "Vaeschanan",
        "Eikev",
        "Re'eh",
        "Shoftim",
        "Ki Seitzei",
        "Ki Savo",
        "Nitzavim",
        "Vayeilech",
        "Ha'Azinu",
        "Vayakhel Pekudei",
        "Tazria Metzora",
        "Achrei Mos Kedoshim",
        "Behar Bechukosai",
        "Chukas Balak",
        "Matos Masei",
        "Nitzavim Vayeilech"
    ];
    const hebrewParshiyos = [
        "בראשית",
        "נח",
        "לך לך",
        "וירא",
        "חיי שרה",
        "תולדות",
        "ויצא",
        "וישלח",
        "וישב",
        "מקץ",
        "ויגש",
        "ויחי",
        "שמות",
        "וארא",
        "בא",
        "בשלח",
        "יתרו",
        "משפטים",
        "תרומה",
        "תצוה",
        "כי תשא",
        "ויקהל",
        "פקודי",
        "ויקרא",
        "צו",
        "שמיני",
        "תזריע",
        "מצרע",
        "אחרי מות",
        "קדושים",
        "אמור",
        "בהר",
        "בחקתי",
        "במדבר",
        "נשא",
        "בהעלתך",
        "שלח לך",
        "קרח",
        "חוקת",
        "בלק",
        "פינחס",
        "מטות",
        "מסעי",
        "דברים",
        "ואתחנן",
        "עקב",
        "ראה",
        "שופטים",
        "כי תצא",
        "כי תבוא",
        "ניצבים",
        "וילך",
        "האזינו",
        "ויקהל פקודי",
        "תזריע מצרע",
        "אחרי מות קדושים",
        "בהר בחקתי",
        "חוקת בלק",
        "מטות מסעי",
        "ניצבים וילך"
    ];
}